on:
  workflow_dispatch:
    branches: [master]
  repository_dispatch:
    types: 
      - build-and-publish

jobs:
  build:
    name: hoge
    runs-on: ubuntu-18.04
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: geny7i/aa-soko
          token: ${{ secrets.PERSONAL_TOKEN }}
      - run: ls
